# Install
pip install open3d
# Requirements
Python >=3.7 and Python <=3.10


In [1]:
import open3d as o3d
import numpy as np

ModuleNotFoundError: No module named 'open3d'

In [13]:
# Defining the path to the 3D model file.
mesh_path = "data/g20.ply"
# Reading the 3D model file as a 3D mesh using open3d.
mesh = o3d.io.read_triangle_mesh(mesh_path)
# Visualizing the mesh.
draw_geoms_list = [mesh]
o3d.visualization.draw_geometries(draw_geoms_list)

In [14]:
# Defining the path to the 3D model file.
mesh_path = "data/g20__.ply"
# Reading the 3D model file as a 3D mesh using open3d.
mesh = o3d.io.read_triangle_mesh(mesh_path)
# Visualizing the mesh.
draw_geoms_list = [mesh]
o3d.visualization.draw_geometries(draw_geoms_list)

In [15]:
# Compute centroid of the mesh
centroid = np.asarray(mesh.get_center())
print(f"Centroid coordinates {centroid}")
# Translate the mesh to the origin
mesh.translate([3,2,4])
print(f"New centroid coordinates  {np.asarray(mesh.get_center())}")

Centroid coordinates [-0.67194498  0.61908907  1.60159157]
New centroid coordinates  [2.32805502 2.61908907 5.60159157]


In [16]:
#Function that computes the surface area of the mesh, i.e. the sum of the individual triangle surfaces.
print(f"Mesh area: {mesh.get_surface_area()}")


Mesh area: 5864.695406163586


In [ ]:
#Function that computes the volume of the mesh.
print(f"Mesh Volume:{mesh.get_volume()}")

In [17]:
# Cropping the car mesh using its bouding box to remove its right half (positive Z-axis).
bbox = mesh.get_axis_aligned_bounding_box()
print(bbox)
bbox_points = np.asarray(bbox.get_box_points())
print(bbox_points)
bbox_points[:, 2] = np.clip(bbox_points[:, 2], a_min=None, a_max=0)
print(bbox_points[:, 2])
#Create a bounding box volume
bbox_cropped = o3d.geometry.AxisAlignedBoundingBox.create_from_points(o3d.utility.Vector3dVector(bbox_points))
bbox2 = bbox_cropped.get_axis_aligned_bounding_box()
print(bbox2)
# crop the mesh
cropped_mesh = mesh.crop(bbox_cropped)
o3d.visualization.draw_geometries([cropped_mesh])


AxisAlignedBoundingBox: min: (-8.3423, -19.6606, -23.2261), max: (11.4241, 26.7002, 42.1789)
[[ -8.34229565 -19.66055489 -23.2260952 ]
 [ 11.42413998 -19.66055489 -23.2260952 ]
 [ -8.34229565  26.70023346 -23.2260952 ]
 [ -8.34229565 -19.66055489  42.17887497]
 [ 11.42413998  26.70023346  42.17887497]
 [ -8.34229565  26.70023346  42.17887497]
 [ 11.42413998 -19.66055489  42.17887497]
 [ 11.42413998  26.70023346 -23.2260952 ]]
[-23.2260952 -23.2260952 -23.2260952   0.          0.          0.
   0.        -23.2260952]
AxisAlignedBoundingBox: min: (-8.3423, -19.6606, -23.2261), max: (11.4241, 26.7002, 0)


In [11]:

# Load the first mesh from file
mesh1 = o3d.io.read_triangle_mesh( "g20.ply")

# Load the second mesh from file
mesh2 = o3d.io.read_triangle_mesh("g20__.ply")

# Convert the meshes to point clouds
pcd1 = mesh1.sample_points_uniformly(number_of_points=1000)
pcd2 = mesh2.sample_points_uniformly(number_of_points=1000)

# Compute the distances between the point clouds
distances = pcd1.compute_point_cloud_distance(pcd2)

# Convert distances to a NumPy array
distances_toarray = np.asarray(distances)

# Print the average distance
average_distance = distances_toarray.mean()
print("Average Distance:", average_distance)

Average Distance: 1.2685634679918003
